// ==UserScript==
// @name		BLIPalacz (j3)
// @namespace	http://jakub300.name/blipalacz
// @description	Dopala blipa :)
// @include		http://blip.pl/dashboard*
// @include		http://blip.pl/users/*/dashboard*
// @include		http://www.blip.pl/dashboard*
// @include		http://www.blip.pl/users/*/dashboard*
// @include		http://blip.pl/tags/*
// @include		http://www.blip.pl/
// @include		http://www.blip.pl/bliposphere
// @include		http://blip.pl/
// @include		http://blip.pl/bliposphere
// @include		http://help.gadu-gadu.pl/errors/blip/
// @include		http://czydziala.gadu-gadu.pl/blip/
// ==/UserScript==
// Generated: 1300207440 (2011-03-15 17:44:00)
try{blipalacz={};blipalacz.version="3.2";blipalacz.version_timestamp=1300207435;blipalacz.version_type="new-alpha";blipalacz._events={};blipalacz._set={};blipalacz._set_val={};blipalacz._sto={};blipalacz._start=function(){blipalacz.browser="FF";if(blipalacz.browser=="FF"){var a=GM_getValue("storage");if(a!==undefined)blipalacz._sto=JSON.parse(a)}if(blipalacz.storage.get("_set_val"))blipalacz._set_val=blipalacz.storage.get("_set_val");blipalacz.zalogowany=document.querySelector(".login-data").innerHTML;
blipalacz.zalogowany=blipalacz.zalogowany.split(" ");blipalacz.zalogowany=blipalacz.zalogowany[10].replace(/\n/,"");blipalacz.token=document.querySelector("#authenticity_token").innerHTML.replace('"',"").replace('"',"").replace(/\n/,"").replace(/\n/,"").replace(/ /gi,"");blipalacz.nick=document.querySelector("#profile-info > h1")?document.querySelector("#profile-info > h1").innerHTML:false;if(document.querySelector("#observed-and-observing-box")){document.querySelector("#observed-and-observing-box").innerHTML+=
'<div id="blipalacz-box" style=""><div class="transparent-box-rounding"></div><div class="transparent-box"><ul class="tab-bar"><li><h2 class="single">Blip dopalony przez <a href="http://kubofonista.net/blipalacz">BLIPALACZ</a></h2></li></ul><center><font style="color:#222222; font-size:85%; margin:5px;">Uzywasz wersji: '+blipalacz.version+'<br />???<div id="blipalacz-ver"></div><div id="blipalacz-workplace"></div><font size=1>BLIPalacz uzyty juz ??? razy :)<br />&copy; 2010 <a href="http://blip.pl/users/kubofonista/dashboard">^Kubofonista</a></font><br /><font size="1"><a id="blipalacz-showsets" href="javascript:void(0);" title="Wyswietla konfiguracje BLIPalacza">Ustawienia wtyczki &raquo;</a></font><br /><div id="blipalacz-sets" style="display:none"></div></font></center></div><div class="transparent-box-rounding-bottom"></div></div>';
document.querySelector("#blipalacz-showsets").addEventListener("click",blipalacz._togglesettings,false)}blipalacz._event("start");blipalacz._event("newblips");setInterval(function(){blipalacz._event("newblips")},1E3)};blipalacz.on=function(a,b){blipalacz._events[a]||(blipalacz._events[a]=[]);blipalacz._events[a].push(b);return true};blipalacz._event=function(a){if(blipalacz._events[a]){var b=0;for(a=blipalacz._events[a];b<a.length;b++)a[b]()}};blipalacz.storage={};blipalacz.storage.get=function(a){return blipalacz._sto[a]};
blipalacz.storage.set=function(a,b){blipalacz._sto[a]=b;blipalacz.browser=="FF"&&GM_setValue("storage",JSON.stringify(blipalacz._sto));return true};blipalacz.settings={};blipalacz.settings.add=function(a,b,e){if(blipalacz._set[a])return false;if(b!="on"&&b!="off")return false;blipalacz._set[a]=b;if(!document.querySelector("#blipalacz-sets"))return true;b=document.createElement("div");b.innerHTML=e+" - ";b.innerHTML+=blipalacz.settings.get(a)=="on"?"w\u0142\u0105czone":"wy\u0142\u0105czone";b.innerHTML+=
" (";e=document.createElement("a");e.href="javascript:void(0)";e.setAttribute("opcja",a);e.addEventListener("click",blipalacz._switchsettings,false);e.innerHTML="zmie\u0144";b.appendChild(e);a=document.createTextNode(")");b.appendChild(a);document.querySelector("#blipalacz-sets").appendChild(b);return true};blipalacz.settings.get=function(a){if(!blipalacz._set[a])return false;if(blipalacz._set_val[a])return blipalacz._set_val[a];return blipalacz._set[a]};blipalacz.settings.set=function(a,b){if(!blipalacz._set[a])return false;
blipalacz._set_val[a]=b;blipalacz.storage.set("_set_val",blipalacz._set_val);return true};blipalacz._togglesettings=function(){if(document.querySelector("#blipalacz-sets").style.display=="none")document.querySelector("#blipalacz-sets").style.display="block";else document.querySelector("#blipalacz-sets").style.display="none"};blipalacz._switchsettings=function(){var a=this.getAttribute("opcja"),b=blipalacz.settings.get(a);if(b=="on")blipalacz.settings.set(a,"off");else b=="off"&&blipalacz.settings.set(a,
"on");location.reload()};blipalacz.p={};blipalacz.on("start",function(){if(document.querySelector("#observed-and-observing-box")){var a=blipalacz.storage.get("menedzer-data");if(a==undefined){blipalacz.storage.set("menedzer-data","");a=""}a=a.split("!@!");var b="",e,d;for(e in a){d=a[e].split("@!@");if(d[1]!=undefined)b+='<form method="post" id="'+e+'" action="http://blip.pl/sessions"><input type="hidden" name="logging_in_user[login]" id="logging_in_user[login]['+e+']" value="'+d[0]+'"/><input type="hidden" name="logging_in_user[password]" id="logging_in_user[password]['+
e+']" value="'+d[1]+'"/>'+d[0]+'<input type="submit" value="Zaloguj &raquo;" style="font-size:9px; border: none; background:none; padding-left:1px;"/><br /></form>';d=""}e=b+'<br /><a id="menedzer-add" href="javascript:void(0);">Dodaj kolejne konto &raquo;</a><br /><a id="menedzer-delall" href="javascript:void(0);">Usun konta &raquo;</a><div id="menedzer-addacc" style="display:none;"><br /><form id="menedzer-form">Login: <input id="menedzer-login"><br />Haslo: <input id="menedzer-haslo" type="password"><br /><input type="submit" value="Zapisz" size="9"></form></div>';
a=document.createElement("div");a.id="blipalacz-manager-box";a.innerHTML='<div class="transparent-box-rounding"></div><div class="transparent-box"><ul class="tab-bar"><li><h2 class="single">Menedzer kont BLIPowych (<a href="javascript:void(0);" id="menedzer-info">?</a>)</h2></li></ul><center><font style="color:#222222; font-size:85%;">'+e+'</font></center></div><div class="transparent-box-rounding-bottom"></div>';document.querySelector("#observed-and-observing-box").appendChild(a);document.querySelector("#menedzer-info").addEventListener("click",
function(){alert('Menedzer kont BLIPowych to dodatek dostarczony przez BLIPalacza. \r\n Umozliwia on zarzadzanie swoimi blipowymi kontami. \r\n Nie musisz pamietac hasel do kont swoich bot\u00f3w. Poprostu je dodaj i klikaj "Zaloguj sie" ;) \r\n\r\n Prywatnosc: Hasla sa zapisywane TYLKO w twojej przegladarce i NIGDY NIE SA NIGDZIE PRZESYLANE');return false},false);document.querySelector("#menedzer-add").addEventListener("click",function(){blipalacz.p.accountmanager.toggle();alert("Po dodaniu konta wejda na liste po odswiezeniu strony");
return false},false);document.querySelector("#menedzer-delall").addEventListener("click",function(){blipalacz.storage.set("menedzer-data","");alert("Konta usuniete. Odswiez strone :)");return false},false);document.querySelector("#menedzer-form").addEventListener("submit",function(){var c=document.querySelector("#menedzer-login").value+"@!@"+document.querySelector("#menedzer-haslo").value+"!@!",f=blipalacz.storage.get("menedzer-data");f==undefined?blipalacz.storage.set("menedzer-data",c):blipalacz.storage.set("menedzer-data",
f+c);document.querySelector("#menedzer-login").value="";document.querySelector("#menedzer-haslo").value="";return false},false)}});blipalacz.p.accountmanager={};blipalacz.p.accountmanager.toggle=function(){var a=document.querySelector("#menedzer-addacc");a.style.display=a.style.display=="none"?"block":"none"};blipalacz.on("start",function(){blipalacz.settings.add("bliposfera","on","Bliposfera: czytalno\u015b\u0107");blipalacz.settings.add("bliposfera_cytaty","on","Blipospera: rozwijaj cytaty");var a=
blipalacz.settings.get("bliposfera")=="on",b=blipalacz.settings.get("bliposfera_cytaty")=="on";if((document.location.href=="http://blip.pl/bliposphere"||document.location.href=="http://blip.pl"||document.location.href=="http://www.blip.pl/bliposphere"||document.location.href=="http://www.blip.pl")&&(a==1||b==1))blipalacz.on("newblips",function(){var e=document.querySelectorAll(".body"),d=document.querySelectorAll(".status > a"),c=e.length,f,g,h,i,j,k=blipalacz.settings.get("bliposfera_cytaty")=="on";
for(f=0;f<c;f++){if(e[f].innerHTML.indexOf("<br")==-1&&a==1){g=d[f].getAttribute("title");e[f].innerHTML="<b>"+g+":</b> "+e[f].innerHTML+"<br />"}if(k==1){h=e[f].querySelectorAll("a");for(g=0;g<h.length;g++){i=h[g].getAttribute("title");j=h[g].innerHTML;if(j=="[blip]")h[g].innerHTML="{"+i+"} "}}}})});blipalacz.on("start",function(){blipalacz.settings.add("fastignore","on","Szybkie ignorowanie u\u017cytkownik\u00f3w");var a=blipalacz.settings.get("fastignore")=="on";document.location.href!="http://blip.pl/bliposphere"&&
document.location.href!="http://blip.pl"&&document.location.href!="http://www.blip.pl/bliposphere"&&document.location.href!="http://www.blip.pl"&&a&&blipalacz.on("newblips",function(){var b=document.querySelectorAll(".container"),e=document.querySelectorAll(".container > .toolbar"),d=document.querySelectorAll(".container > .author");b=b.length;for(var c=0,f,g;c<b;c++)if(e[c]){f=e[c].innerHTML;g=d[c];if(g!=undefined)g=g.getAttribute("href").replace("http://blip.pl/users/","").replace("/dashboard",
"");if(f.indexOf("plonk")==-1)g==undefined||g==blipalacz.zalogowany||(e[c].innerHTML+='<span class="divider">&nbsp; | &nbsp;</span> <a class="respond" onclick="var x = confirm(\'Czy napewno chcesz dodac '+g+" do ignorowanych? '); if(x == true) { var f = document.createElement('form'); f.style.display = 'none'; this.parentNode.appendChild(f); f.method = 'POST'; f.action = this.href;var m = document.createElement('input'); m.setAttribute('type', 'hidden'); m.setAttribute('name', '_method'); m.setAttribute('value', 'put'); f.appendChild(m);var s = document.createElement('input'); s.setAttribute('type', 'hidden'); s.setAttribute('name', 'authenticity_token'); s.setAttribute('value', '"+
blipalacz.token+'\'); f.appendChild(s);f.submit(); } return false;" id="ignore" href="/users/'+g+'/ignore"><font style="font-size:7px;">plonk</font></a>')}})});blipalacz.on("start",function(){blipalacz.settings.add("kokpit_cytaty","on","Kokpit: rozwijaj cytaty");blipalacz.settings.add("kokpit_linki","on","Kokpit: rozwijaj linki");var a=blipalacz.settings.get("kokpit_linki")=="on",b=blipalacz.settings.get("kokpit_cytaty")=="on";if(document.location.href!="http://blip.pl/bliposphere"&&document.location.href!=
"http://blip.pl"&&document.location.href!="http://www.blip.pl/bliposphere"&&document.location.href!="http://www.blip.pl"&&(a==1||b==1))blipalacz.on("newblips",function(){for(var e=blipalacz.settings.get("kokpit_linki")=="on",d=blipalacz.settings.get("kokpit_cytaty")=="on",c=document.querySelectorAll(".content > a"),f=c.length,g=0,h;g<f;g++){h=c[g];if(h.getAttribute("done")!=1){var i=h.getAttribute("title"),j=h.innerHTML,k=h.getAttribute("href"),l='<div align="right" style="font-size:10px"><a href="#" onclick="window.BLIP.dashboardInput.quote(\''+
k+"');; return false;\">Cytuj</a></div>";if(j!="[blip]"&&j!="s"&&j.indexOf("^")==-1&&j.indexOf("#")==-1&&e)if(i!=undefined)h.innerHTML=i.match(/(<([^>]+))/ig)?i.replace(/(<([^>]+))/ig,"")+' <font color="red"><b>UWAGA!! LINK ZAWIERA ATAK XSS!!</b></font>':i==""?h.getAttribute("href"):i.replace(/(<([^>]+))/ig,"");if(j=="[blip]"&&d)h.innerHTML='<br /><div style="background-color:#EEEEEE; border:2px dashed #C0C0C0; font-size:10pt; line-height:10pt; padding:5px;"><a href="'+k+'" target="_blank">'+i+"</a>"+
l+"</div>";h.setAttribute("done",1)}}c=document.querySelectorAll(".notice > a");f=c.length;for(g=0;g<f;g++){h=c[g];i=h.getAttribute("title");e=h.getAttribute("href");j=h.innerHTML;if(j=="[blip]")h.innerHTML='<br /><div style="background-color:#EEEEEE; border:2px dashed #C0C0C0; font-size:10pt; line-height:10pt; padding:5px; width:475px"><a href="'+e+'" target="_blank">'+i+"</a></div>"}})});blipalacz.on("start",function(){blipalacz.settings.add("kolorowanietagow","on","Kolorowanie tag\u00f3w");blipalacz.settings.get("kolorowanietagow")==
"on"&&blipalacz.on("newblips",function(){for(var a=document.evaluate("//a[contains(@href, 'blip.pl/tags/') and not(contains(@class, 'tagged')) and not(contains(@class, 'g')) and not(contains(@id, 'tagcloud-content'))]",document,null,6,null),b,e=0;b=a.snapshotItem(e++);){var d=b.href.substr(b.href.indexOf("/tags/")+6),c=blipalacz.p.kolorowanietagow.bgColors[d]?blipalacz.p.kolorowanietagow.bgColors[d]:blipalacz.p.kolorowanietagow.computeBgColor(d);d=blipalacz.p.kolorowanietagow.fgColors[d]?blipalacz.p.kolorowanietagow.fgColors[d]:
blipalacz.p.kolorowanietagow.computeFgColor(d);c="hsl("+c.hue+", "+c.sat+"%, 80%)";var f="color: hsl("+d.hue+", 66%, 33%) !important;";d=b.cloneNode(true);d.className="tagged";d.setAttribute("style",f);f=document.createElement("span");f.className="innerTag";f.style.background=c;f.style.borderColor=c;f.appendChild(d);d=document.createElement("span");d.className="tag";d.style.background=c;d.style.borderColor=c;d.appendChild(f);b.parentNode.replaceChild(d,b)}})});blipalacz.p.kolorowanietagow={};blipalacz.p.kolorowanietagow.fgColors=
{};blipalacz.p.kolorowanietagow.bgColors={};blipalacz.p.kolorowanietagow.computeBgColor=function(a){var b=function(d){var c,f=1742;for(c=0;c<d.length;c++){var g=d.charCodeAt(c);f=(f<<2)+(f<<5)+g%32}return f}(a),e=b%360;blipalacz.p.kolorowanietagow.fgColors[a]={hue:e,sat:50+b%50};return{hue:e,sat:50+b%50}};blipalacz.p.kolorowanietagow.computeFgColor=function(a){var b=function(d){var c,f=59981;for(c=0;c<d.length;c++){var g=d.charCodeAt(c);f=(f<<2)+(f<5)+g%32}return f}(a),e=b%360;blipalacz.p.kolorowanietagow.fgColors[a]=
{hue:e,sat:b%50};return{hue:e,sat:b%50}};blipalacz.on("start",function(){blipalacz.settings.add("komunikatory","on","Linkuj do GG");var a=blipalacz.settings.get("komunikatory")=="on";document.location.href!="http://blip.pl/bliposphere"&&document.location.href!="http://blip.pl"&&document.location.href!="http://www.blip.pl/bliposphere"&&document.location.href!="http://www.blip.pl"&&a&&blipalacz.on("newblips",function(){for(var b=document.querySelectorAll(".content"),e=b.length,d=0,c;d<e;d++){c=b[d];
if(c.getAttribute("done")!=1){c.innerHTML=c.innerHTML.replace(/gg:([0-9]+)/,'<a href="gg://$1" title="Gadu-Gadu" done="1"><img style="border: none; vertical-align: top;" src="http://www.gadu-gadu.pl/users/status.asp?id=$1&styl=1" border="0">$1</a>');c.setAttribute("done",1)}}})});blipalacz.on("start",function(){blipalacz.settings.add("licznikonline","on","Wy\u015bwietlaj licznik os\u00f3b online");if(blipalacz.settings.get("licznikonline")=="on")if(document.querySelector("#observed-and-observing-box")){var a=
document.createElement("center"),b=document.createElement("h4");b.id="online_counter";a.appendChild(b);(b=document.querySelector("#observed-tab"))||(b=document.querySelector("#observing-tab"));b.parentNode.insertBefore(a,b);blipalacz.p.licznikonline.update()}});blipalacz.p.licznikonline={};blipalacz.p.licznikonline.update=function(){var a=document.querySelectorAll("a.active")[0];if(a&&a.href.indexOf("#recommended")>=0)a=document.querySelectorAll("a.active")[1];document.querySelector("#online_counter").innerHTML=
!a||a.href.indexOf("#observing-tab")>=0?"Online: "+document.querySelectorAll(".tracking-user-avatar-active").length+" z "+document.querySelectorAll(".tracking-user-avatar").length:a.href.indexOf("#observed-tab")>=0?"Online: "+document.querySelectorAll(".tracked-user-avatar-active").length+" z "+document.querySelectorAll(".tracked-user-avatar").length:"";setTimeout(blipalacz.p.licznikonline.update,3E3)};blipalacz.on("start",function(){blipalacz.settings.add("oponka_powrot","on","Wracaj z oponki na kokpit");
if(blipalacz.settings.get("oponka_powrot")=="on"&&(document.location.href=="http://help.gadu-gadu.pl/errors/blip/"||document.location.href=="http://czydziala.gadu-gadu.pl/blip/"))document.location.href="http://blip.pl/dashboard"});blipalacz.on("start",function(){blipalacz.settings.add("dmpm_kontynuuj","on","Kontynuuj przy wlasnych dm/pm");var a=blipalacz.settings.get("dmpm_kontynuuj")=="on";document.location.href!="http://blip.pl/bliposphere"&&document.location.href!="http://blip.pl"&&document.location.href!=
"http://www.blip.pl/bliposphere"&&document.location.href!="http://www.blip.pl"&&a&&blipalacz.on("newblips",function(){for(var b=document.querySelectorAll("span.respond"),e=b.length,d=0,c,f,g,h,i;d<e;d++){c=b[d];f=c.parentNode.parentNode.querySelectorAll("span.nick");g=c.parentNode.parentNode.querySelectorAll("span.private-mark");for(h=0;h<f.length;h++){i=f[h].querySelectorAll("a");if(i.length==2){i=i[0].innerHTML;i=g.length==1?"<a onclick=\"window.BLIP.dashboardInput.respondTo('"+i+'\',true);; return false;" href="#" class="respond">kontynuuj</a>':
"<a onclick=\"window.BLIP.dashboardInput.respondTo('"+i+'\',false);; return false;" href="#" class="respond">kontynuuj</a>';c.innerHTML=i}}}})});blipalacz.on("start",function(){blipalacz.settings.add("userstats","on","Wy\u015bwietlaj informacje rankingowe na kokpitach");if(blipalacz.settings.get("userstats")=="on"){var a=document.location.href;if(a.match("http://blip.pl/dashboard")||a.match("http://blip.pl/users"))GM_xmlhttpRequest({method:"GET",url:"http://api.blipi.pl/blipalacz/stats/"+blipalacz.nick,
headers:{"User-agent":"BLIPalacz"},onload:function(b){var e=JSON.parse(b.responseText,function(h,i){var j;if(i&&typeof i==="object"){j=i.type;if(typeof j==="string"&&typeof window[j]==="function")return new window[j](i)}return i});b=e.rank;var d=e.rankchange,c=e.trackedbychange,f=e.trackedby,g=e.citations;e=e.mentions;if(d==0||d==undefined)d="";else if(d>0){d+="";d=d.replace("-","");d=' <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kMGQwkE21IS08AAAFASURBVCjPrZIxSwNBEIXf7ia5u72LMTkTEg5Ro4WVf0SraJM/IGITFMukshDEBCwECRibNIKVhYitv8JWsBETlCho7nbHRu8M5NTCgQdv9/ExAzNATHUuD+n4vElxeSIuuOvdYPD0FheDj/tsdKo0M5+Bt5jGdmuN/gTudTepNJ0EFwxcMEzNcdSP1ulXUMg+pJ0AKQ2lCIYjoOXDzx3rnQq5eQtKEZQi6E9lSyZqrRUaCzZOquR5NijQ30ShCrMWtpqrNAIenO3QpAuIBIPWFOqrs1IELhicvMZuu0YAwLrXbbq9v0IuZ4BzBiMVTd97jdYRDAnK13h+9LFUXgYbWcNphYpFKwIH76F/6Q+xv3HBxh5AWhZgpSLQMaOOXAbxl+NOlJGRyWg1zA+9DRUPFrILsKQI32ZSh943NP6lPgAyQ4PF9853mAAAAABJRU5ErkJggg=="><font color="green">['+
d+"]</font>"}else d=' <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kMGQwqOF93n4EAAAFZSURBVCjPnZA7SwNBFIXPzO7mYWI6IUYEEREL3yKKiJUQEaJREFJZWERU1EaiP0HstBH8BXapBav8ABsFDcFAMIIgSViSmMfsztjt7CYsiKe6c+58XM4B/ilifzyl70VIkRb1UGuuNE3MxRPWUrWDRuEVileRoE/O7RpzXHSA7DMH1S8tGtTkrtJyB83SF0hAWorhkWC56cz4eHctfjJpDAVV+AmBX5UZ1V4J1hiHKQSKVQbvwiboavKUmINjYBwOqFNBjcLggBkexfLeMaEAMLxzRPJMQ8MQrmCDcxQaCsJbhwQAKABMzU5gYHufvOjMFcyVW+iLJcnk9DgsEACWYnH0LK6RfN3ogj6qDL6ZKObXN2Tj9g/Rkwt8hyIoM255ettEKdCPlYOUVcBbUXeCADCye06yLQ2MCxhC4L2uIJI4c0BdF+15n3WGbEeuP+nh5lJkbq9ca/4FqcF15bkSkS4AAAAASUVORK5CYII="><font color="red">['+
d+"]</font>";if(c==0|c==undefined)c="";else if(c>0){c+="";c=c.replace("-","");c=' <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kMGQwkE21IS08AAAFASURBVCjPrZIxSwNBEIXf7ia5u72LMTkTEg5Ro4WVf0SraJM/IGITFMukshDEBCwECRibNIKVhYitv8JWsBETlCho7nbHRu8M5NTCgQdv9/ExAzNATHUuD+n4vElxeSIuuOvdYPD0FheDj/tsdKo0M5+Bt5jGdmuN/gTudTepNJ0EFwxcMEzNcdSP1ulXUMg+pJ0AKQ2lCIYjoOXDzx3rnQq5eQtKEZQi6E9lSyZqrRUaCzZOquR5NijQ30ShCrMWtpqrNAIenO3QpAuIBIPWFOqrs1IELhicvMZuu0YAwLrXbbq9v0IuZ4BzBiMVTd97jdYRDAnK13h+9LFUXgYbWcNphYpFKwIH76F/6Q+xv3HBxh5AWhZgpSLQMaOOXAbxl+NOlJGRyWg1zA+9DRUPFrILsKQI32ZSh943NP6lPgAyQ4PF9853mAAAAABJRU5ErkJggg=="><font color="green">('+
c+")</font>"}else c=' <img src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kMGQwqOF93n4EAAAFZSURBVCjPnZA7SwNBFIXPzO7mYWI6IUYEEREL3yKKiJUQEaJREFJZWERU1EaiP0HstBH8BXapBav8ABsFDcFAMIIgSViSmMfsztjt7CYsiKe6c+58XM4B/ilifzyl70VIkRb1UGuuNE3MxRPWUrWDRuEVileRoE/O7RpzXHSA7DMH1S8tGtTkrtJyB83SF0hAWorhkWC56cz4eHctfjJpDAVV+AmBX5UZ1V4J1hiHKQSKVQbvwiboavKUmINjYBwOqFNBjcLggBkexfLeMaEAMLxzRPJMQ8MQrmCDcxQaCsJbhwQAKABMzU5gYHufvOjMFcyVW+iLJcnk9DgsEACWYnH0LK6RfN3ogj6qDL6ZKObXN2Tj9g/Rkwt8hyIoM255ettEKdCPlYOUVcBbUXeCADCye06yLQ2MCxhC4L2uIJI4c0BdF+15n3WGbEeuP+nh5lJkbq9ca/4FqcF15bkSkS4AAAAASUVORK5CYII="><font color="red">('+
c+")</font>";if(f==0||f==undefined)document.querySelector("#profile-info > .clearfix").innerHTML+='<dl style="width:100%"><dt class="small">Obserwujacy: 0/brak danych</dt></dl>';else document.querySelector("#profile-info > .clearfix").innerHTML+='<dl style="width:100%"><dt class="small">Obserwujacy: '+f+c+"</dt></dl>";if(b==0||b==undefined)document.querySelector("#profile-info > h1").innerHTML=blipalacz.nick+' <span style="font-size:11px; text-align:right; position: relative; top: -2px;">(top n/a)</span>';
else document.querySelector("#profile-info > h1").innerHTML=blipalacz.nick+' <span style="font-size:11px; text-align:right; position: relative; top: -2px;">(top '+b+d+')</span><br /><font style="font-size: 8.5px;">Cytowan: '+g+" | Wzmianek: "+e+"</font>"}})}});blipalacz.on("start",function(){blipalacz.settings.add("ukryj_polecane","on","Ukryj: polecane");blipalacz.settings.add("ukryj_cloudtag","on","Ukryj: chmurka tag\u00f3w");blipalacz.settings.add("ukryj_reklamagraf","on","Ukryj: reklama graficzna");
blipalacz.settings.get("ukryj_polecane")=="on"&&GM_addStyle("#recommended-box {display:none; } #beginners-recommended-box {display:none; }");blipalacz.settings.get("ukryj_reklamagraf")=="on"&&GM_addStyle('#sidebar a img[alt="Button"] {display: none; }');if(blipalacz.settings.get("ukryj_cloudtag")=="on")document.location.href.match("http://blip.pl/tags/")||GM_addStyle("#tagcloud-box {display:none;}")});blipalacz.on("start",blipalacz.p.aktualizator.sprawdz);blipalacz.p.aktualizator={};blipalacz.p.aktualizator.sprawdz=
function(){blipalacz.version_timestamp===false||!blipalacz.p.aktualizator.url[blipalacz.version_type]||GM_xmlhttpRequest({method:"GET",url:blipalacz.p.aktualizator.url[blipalacz.version_type],onload:function(a){try{if(JSON.parse(a.responseText).timestamp>blipalacz.version_timestamp){alert("Strza\u0142ka! Dost\u0119pna jest nowsza wersja. Po kliknieciu OK ujrzysz okienko instalacyjne :)");window.location=blipalacz.p.aktualizator.urld[blipalacz.version_type]}}catch(b){}}})};blipalacz.p.aktualizator.url=
{};blipalacz.p.aktualizator.url.stable=false;blipalacz.p.aktualizator.url.nightly="https://github.com/kubofonista/BLIPalacz/raw/nightly/ver_nightly.txt";blipalacz.p.aktualizator.url["new-alpha"]="https://github.com/jakub300/BLIPalacz/raw/nightly/ver_nightly.txt";blipalacz.p.aktualizator.urld={};blipalacz.p.aktualizator.urld.stable="https://github.com/kubofonista/BLIPalacz/raw/master/blipalacz.user.js";blipalacz.p.aktualizator.urld.nightly="https://github.com/kubofonista/BLIPalacz/raw/nightly/blipalacz.user.js";
blipalacz.p.aktualizator.urld["new-alpha"]="https://github.com/jakub300/BLIPalacz/raw/nightly/blipalacz.user.js";blipalacz._start()}catch(e$$6){alert(e$$6)};
